#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

v1 = ARGV[0]
v2 = ARGV[1]
puts v1
puts v2
system "/usr/lib/jvm/jdk-8-oracle-x64/bin/java  -cp bin:lib/antlr-4.4-complete.jar Main #{v1} #{v2}"
#system "java  -cp bin:lib/antlr-4.4-complete.jar Main #{v1} #{v2}" 
exit($?.exitstatus)
