#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

v1 = ARGV[0]
puts v1
system "/usr/lib/jvm/jdk-8-oracle-x64/bin/java  -cp bin:lib/antlr-4.4-complete.jar Main #{v1}" 
exit($?.exitstatus)
